# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gclid.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gclid.proto',
  package='',
  serialized_pb='\n\x0bgclid.proto\"\x1a\n\x05Gclid\x12\x11\n\ttimestamp\x18\x01 \x02(\x03')




_GCLID = _descriptor.Descriptor(
  name='Gclid',
  full_name='Gclid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Gclid.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=15,
  serialized_end=41,
)

DESCRIPTOR.message_types_by_name['Gclid'] = _GCLID

class Gclid(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GCLID

  # @@protoc_insertion_point(class_scope:Gclid)


# @@protoc_insertion_point(module_scope)
